### ISSUE TITLE
flag-ms.py: NameError: name 'cmp' is not defined

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/owlcat#56]
```
(meerkathi) oms@young:~/projects/OldDevils/msdir-reobs$ flag-ms.py --stats -v 2 1568538661_sdp_l0.ms
Warning: No Cattery package found.
If you have Cattery in a non-standard location, please set the MEQTREES_CATTERY_PATH environment
variable to point to it.
2.7Gb Flagger(Flagger.py:323:_reopen): opened MS /home/oms/projects/OldDevils/msdir-reobs/1568538661_sdp_l0.ms, 6041010 rows
2.7Gb Flagger(Flagger.py:329:_reopen): this MS has proper bitflag columns of type 'int'
Traceback (most recent call last):
  File "/home/oms/.venv/meerkathi/bin/flag-ms.py", line 296, in <module>
    flagger = Flagger(msname, verbose=options.verbose, timestamps=options.timestamps, chunksize=options.chunk_size)
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/Owlcat/Flagger.py", line 311, in __init__
    self._reopen()
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/Owlcat/Flagger.py", line 333, in _reopen
    self.flagsets = Flagsets(ms)
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/Owlcat/Flagger.py", line 177, in __init__
    bitwise_order.sort(key=cmp_to_key(lambda a, b: cmp(self.bits[a], self.bits[b])))
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/Owlcat/Flagger.py", line 177, in <lambda>
    bitwise_order.sort(key=cmp_to_key(lambda a, b: cmp(self.bits[a], self.bits[b])))
NameError: name 'cmp' is not defined
```

**Comment by o-smirnov** [comment]
Just a mild py2 hangover.
