### ISSUE TITLE
fitstool.py broken in current master? (astropy related)

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/owlcat#69]
I reported this here:

https://github.com/ratt-ru/Stimela/issues/634

as what I thought was a container configuration issue, but I think fitstool.py is actually broken.

```
$ fitstool.py -z 10125 img_1591471860_sdp_l0_1024ch_J2103-6200.ms_pcalmask-MFS-image.mask1.fits
Warning: No Cattery package found.
If you have Cattery in a non-standard location, please set the MEQTREES_CATTERY_PATH environment
variable to point to it.
Traceback (most recent call last):
  File "/mnt/home/ianh/venv/owlcat/bin/fitstool.py", line 4, in <module>
    __import__('pkg_resources').run_script('owlcat==1.6.2', 'fitstool.py')
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/owlcat-1.6.2-py3.6.egg/EGG-INFO/scripts/fitstool.py", line 31, in <module>
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/owlcat-1.6.2-py3.6.egg/Owlcat/FitsTool.py", line 508, in main
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/astLib-0.11.4-py3.6-linux-x86_64.egg/astLib/astWCS.py", line 339, in pix2wcs
    raise Exception("Not handling NAXIS > 3 with astropy.wcs shim")
Exception: Not handling NAXIS > 3 with astropy.wcs shim
```

**Comment by o-smirnov** [comment]
Looks like astropy has gotten more fussy in later versions... Can you point me to the FITS image?

**Comment by IanHeywood** [comment]
It's on an Oxford machine, but any wsclean image will trigger the bug.

**Comment by o-smirnov** [comment]
Wavelengthism! It looks like at some point in the recent past ``astropy.wcs`` decided to make itself incompatible with radio images. :( 

I've checked in an Ugly Kludge. Please test the ``issue-69`` branch and let me know if it helps. We'll push out a release if this fixes the problem.

**Comment by IanHeywood** [comment]
A different one this time...

```
(owlcat) ianh@ndidi:/ndidi/ianh/ORC1$ fitstool.py -z 10125 IMAGES/img_1591471860_sdp_l0_1024ch_J2103-6200.ms_pcalmask-MFS-image.mask1.fits
Warning: No Cattery package found.
If you have Cattery in a non-standard location, please set the MEQTREES_CATTERY_PATH environment
variable to point to it.
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/mnt/home/ianh/venv/owlcat/bin/fitstool.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/home/ianh/Software/owlcat-issue-69/Owlcat/bin/fitstool.py", line 31, in <module>
    main()
  File "/mnt/home/ianh/Software/owlcat-issue-69/Owlcat/FitsTool.py", line 516, in main
    world = wcs.wcs_pix2world(pixcoord, 0)  # get WCS of center pixel
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 1391, in wcs_pix2world
    'output', *args, **kwargs)
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 1293, in _array_converter
    return _return_single_array(xy, origin)
  File "/mnt/home/ianh/venv/owlcat/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 1272, in _return_single_array
    "of shape (N, {})".format(self.naxis))
ValueError: When providing two arguments, the array must be of shape (N, 4)
```

**Comment by IanHeywood** [comment]
> Wavelengthism! It looks like at some point in the recent past astropy.wcs decided to make itself incompatible with radio images. :(

Also, whaaaaat?

**Comment by o-smirnov** [comment]
OK, try again...

Perhaps I speak too harshly. They just changed the interface so all FITS axes are now mandatory parts of the world coordinate system. So whereas before you could ask it to convert 2D sky coordinates back and forth without worrying about the other axes of the cube, now it wants a frequency and Stokes coordinate as well, even if those things aren't part of the conversion.

**Comment by IanHeywood** [comment]
Working now, thanks chief.
